-- Seed real sponsor names migrated from the legacy LeagueLineup site's
-- sponsor page. The source content listed sponsor names only, with no
-- per-sponsor tier or dollar amount, so every row defaults to the 'black'
-- tier with a note flagging it for admin confirmation. The public sponsor
-- wall (SponsorsShowcase) does not render tier, so this only affects
-- internal admin views until someone fills in the real tier/amount.
INSERT INTO public.sponsors (name, tier, active, notes) VALUES
  ('AA Jacobs Supply', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Action Packaging', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('All-Tech Decorating', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('AllianceCo', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Arete Advising / Christopher Klotz', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Array', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Ascher Brothers', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Atomatic Mechanical Services', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Bernhard Woodwork Ltd.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Break Thru Enterprises', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Commercial Carpet Consultants', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Consolidated Flooring', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Continental Electrical Construction Company', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Core Flooring Inc.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('David Architectural Metal', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Flooring Resources Corporation', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('GCS Supply Inc', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Great Lakes Plumbing & Heating Co.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Hamilton Health Performance', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('In & Out Painting, Inc.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Integrated Specialty Contractors', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Inter Ocean Cabinet Company', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Loeffel Steel Group', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Marvin Feig & Associates', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('New American Funding - Brian Augustine Team', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Parenti & Raffaelli', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Performance Contracting Inc. (PCI)', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Prime Scaffold Inc.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Proline Mechanical Inc.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Ralph H Simpson Company', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Redmond Construction Corp.', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('RG Construction Services', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Shan''s One of a Kind', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Skyline Construction', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Slate Demolition', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Switch Rail Safety Systems, LLC', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Team Tortorice Wrestling', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('The Augustine Mortgage Team', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('The Lift Guy', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Titan Electric LLC', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Westside Mechanical Group', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('Worlds Oldest Sport', 'black', true, 'Migrated from legacy site; tier unconfirmed.'),
  ('FE Moran, Inc.', 'black', true, 'Migrated from legacy site; tier unconfirmed.');
